ignore:
  - "selfhost/tmp/*"
  - "**/*":
    - Layout/ExtraSpacing
    - Layout/SpaceBeforeSemicolon
    - Style/GlobalVars
    - Style/MethodCallWithoutArgsParentheses
    - Style/StderrPuts
    # TODO
    - Layout/ArgumentAlignment
    - Layout/ArrayAlignment
    - Layout/EmptyLinesAroundClassBody
    - Layout/FirstArgumentIndentation
    - Layout/FirstArrayElementIndentation
    - Layout/HeredocIndentation
    - Layout/MultilineArrayBraceLayout
    - Layout/MultilineMethodCallIndentation
    - Layout/SpaceAroundOperators
    - Layout/SpaceBeforeBlockBraces
    - Layout/SpaceBeforeComma
    - Layout/SpaceInsideBlockBraces
    - Layout/SpaceInsideHashLiteralBraces
    - Layout/SpaceInsideParens
    - Layout/SpaceInsideRangeLiteral
    - Layout/SpaceInsideReferenceBrackets
    - Layout/SpaceInsideStringInterpolation
    - Lint/LiteralAsCondition
    - Lint/UselessAssignment
    - Performance/ReverseEach
    - Performance/StringReplacement
    - Style/DefWithParentheses
    - Style/EmptyCaseCondition
    - Style/EmptyElse
    - Style/HashSyntax
    - Style/IdenticalConditionalBranches
    - Style/ParenthesesAroundCondition
    - Style/RedundantParentheses
    - Style/SelfAssignment
    - Style/Semicolon
    - Style/SlicingWithRange
    - Style/StringLiterals
    - Style/TernaryParentheses
    - Style/YodaCondition
